INSERT INTO Ambulatorio (Nome) VALUES 
('Dermatologia'),
('Radiologia'),
('Urologia'),
('Pediatria'),
('Chirurgia'),
('Cardiologia'),
('Ginecologia'),
('Allergologia'),
('Psichiatria'),
('Ortopedia'),
('Neurologia'),
('Pronto Soccorso'),
('Geriatria'),
('Oculistica');
