SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE Referto;
INSERT INTO Referto(Codice, Contenuto) VALUES
(1, "Ciclista investito da auto. Caduta a terra con trauma cranico, iniziale amnesia, attualmente ricorda l'accaduto: riferisce di essere stato stretto in una strettoia e di essere quindi stato toccato e caduto di conseguenza. Dolorabilità in sede cervicale. Diagnosi: Frattura scomposta della clavicola sinistra, escoriazioni multiple."),
(2,"Esame eseguito con sequenze DP, T1W, T2W e con soppressione del grasso secondo piani multipli. Non sono apprezzabili alterazionia livello delle strutture ossee dell'articolazione scapolo omerale. Si prescrive Artbxa28 20mg al giorno dopo i pasti."),
(3, "Esami ematochimici nella norma, non sono state riscontrate alterazioni. Prescrivo isotretinoina 10mg per un mese. Al termine del mese il paziente tornerà per un controllo."),
(4, "Sono stati analizzati nuovamente gli esami, la terapia sta procedendo bene. Aumento la dose a 20mg per un mese, dopo questo tempo il paziente tornerà per un nuovo controllo."),
(5, "La paziente segnala un forte dolore alle articolazioni inferiori a seguito di una caduta, dopo una visita preliminare posso confermare che si tratti di un semplice strappo muscolare. Pertanto prescrivo ARtex pomata e consiglio una settimana a riposo senza fare ulteriori sforzi."),
(6, "Valori di PA ben controllati, incremento ponderale a seguito della terapia EV. Si conferma l'attuale terapia. Controllo tra 18 mesi con gli esami del sangue precedentemente prescritti."),
(7, "Studio contrastografico bifasico mirato in particolare alla valutazione dei vasi cervicali. In riferimento al quesito diagnostico si conferma dominanza venosa giugulare destra, con minor calibro della vena giugulare sinistra ove, tuttavia, non sono dimostrabili franchi fenomeni trombotici. Prescrivo analisi RVA, T87, PBWA, E3WSC, PP0E. Appena le analisi sono pronte prenotarsi per visita di controllo"),
(8, "Dalle analisi riportate non sono dimostrabili espansi con carattere di impregnazione patologico; areola di tessuto modicamente iperdenso all'adipe e con margini poco definiti, di circa 15 mm si apprezza a sinistra al confine tra il livello IV di Robbins e la fossa sovraclaveare, senza chiaro carattere di evolutività."),
(9, "Dal controllo odierno si possono notare delle formazioni ad aspetto cistico di circa 5 mm nel contesto della tonsilla linguale sul versante destro. Per il resto, regolare aspetto di lingua, epiglottide, piano glottico e ghiandole salivari maggiori ai piani di scansione esaminati."),
(9, "Modesti fenomeni di inspessimento mucoso interessano le cellette etmoidali e i seni mascellari (in particolare a destra). Non evidenti linee di frattura delle strutture scheletriche"),
(10, "Torace: Non lesioni parenchimali focali attive. Emifreni a curvatura regolare, seni costofrenici basali liberi. SPALLA DX: Non lesioni focali dei capi ossei articolari"),
(11, "Entrambi i muscoli mostrano moderato polimetrismo miofibale con presenza di fibre atrofiche angolari e angloidi e fibre ipertrofiche con rara necrosi e miofagocistosi e fibrosi perimisiale. Non si osservano alterazioni della distribuzione miofibrale e del pattern enzimatico ossidativo."),
(12, "Biopsia muscolare effettuata, i fascetti nervosi instramuscolari non sono visibili. Diagnosi: Moderata atrofia neurogena cronica attiva.")
(13, "Certifico di aver visitato la paziente, già in cura presso questa ASL. Presenta uno stato d'ansia con manifestazione a carattere panico reattivo ad un evento traumatico: riferisce di aver assistito ad una rapina a mano armata sabato scorso, mentre era a fare acquisti in un negozio. Terapia consigliata: xanax gtt 10gtt x 3 die; felison 30 mg 1 cp alla sera; talofen 10-15 gtt al bisogno"),
(14, "Paziente affetto da epatocarcinoma con secondarismi linfonodali addominali e toracici. Attualmente in trattamento con zebrafish per sua spontanea volontà, ritengo utile il trattamento con gasthcl per tre mesi. In caso di anomalie presentarsi il prima possibile per un controllo"),
(15, "Il paziente ha eseguito TC con evidenza di una risposta di alcune lesioni con stazionarità di altre. Alfa-fetoproteina negativa. Ottime condizioni generali."),
(16, "A seguito di un secondo controllo, ritengo utile eseguire nuova TC a tre mesi, con ripetizione dell'alfafetoproteina ogni mese. Se in aumento si anticiperà tale periodo."),
(17, "Indagine effettuata senza e con somministrazione di MdC iodato (lobitridolo) e confrontata con precedente. Non si evidenziano masse o lesioni parenchimali a focolaio in atto. Non versamento pleurico. Non linfoadenopatie ilo-mediastiniche."),
(18, "Al controllo odierno in ambito epatico, in esiti di resezione del VII segmento, non si rilevano lesioni focali oncologicamente significative; permangono immodificate le microcisti biliare epatiche di diametro massimo di circa a 5mm."),
(19, "Immodificate le note linfoadenopatie presenti in sede retroperitoneali, curali e retro aortocavali precedentemente descritte. Non versamento endoaddominale, non lesioni ossee."),
(20, "Non alterazioni densitometriche a livello pancreatico, quesito clinico: follow up oncologico. Note per il paziente: per ogni informazione o chiarimento sugli aspetti medici, può rivolgersi al suo medico curante."),
(21, "
SET FOREIGN_KEY_CHECKS = 1;
